#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v4
# autospec commit: da8b975a5699
#
Name     : git-lfs
Version  : 3.4.1
Release  : 2
URL      : https://github.com/git-lfs/git-lfs/releases/download/v3.4.1/git-lfs-v3.4.1.tar.gz
Source0  : https://github.com/git-lfs/git-lfs/releases/download/v3.4.1/git-lfs-v3.4.1.tar.gz
Source1  : http://localhost/cgit/projects/git-lfs-vendor/snapshot/git-lfs-vendor-3.4.1.tar.xz
Summary  : Packages for git-lfs for Enterprise Linux repository configuration
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause ISC MIT MPL-2.0-no-copyleft-exception
Requires: git-lfs-bin = %{version}-%{release}
Requires: git-lfs-data = %{version}-%{release}
Requires: git-lfs-license = %{version}-%{release}
Requires: git-lfs-man = %{version}-%{release}
BuildRequires : asciidoctor
BuildRequires : go
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This package contains the Extra Packages for Enterprise Linux (EPEL) repository
GPG key as well as configuration for yum.

%package bin
Summary: bin components for the git-lfs package.
Group: Binaries
Requires: git-lfs-data = %{version}-%{release}
Requires: git-lfs-license = %{version}-%{release}

%description bin
bin components for the git-lfs package.


%package data
Summary: data components for the git-lfs package.
Group: Data

%description data
data components for the git-lfs package.


%package license
Summary: license components for the git-lfs package.
Group: Default

%description license
license components for the git-lfs package.


%package man
Summary: man components for the git-lfs package.
Group: Default

%description man
man components for the git-lfs package.


%prep
%setup -q -n git-lfs-3.4.1
cd %{_builddir}
tar xf %{_sourcedir}/git-lfs-vendor-3.4.1.tar.xz
cd %{_builddir}/git-lfs-3.4.1
mkdir -p ./
cp -r %{_builddir}/git-lfs-vendor-3.4.1/* %{_builddir}/git-lfs-3.4.1/./

%build
## build_prepend content
unset CLEAR_DEBUG_TERSE
make -f Makefile GIT_LFS_SHA=unused VERSION=unused PREFIX=unused man
pushd docs
go build -o ./bin/mangen man/mangen.go
./bin/mangen
popd
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1708476775
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}  -f Makefile GIT_LFS_SHA=unused VERSION=unused PREFIX=unused


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1708476775
rm -rf %{buildroot}
## install_prepend content
./bin/git-lfs completion bash > git-lfs.bash
## install_prepend end
mkdir -p %{buildroot}/usr/share/package-licenses/git-lfs
cp %{_builddir}/git-lfs-%{version}/LICENSE.md %{buildroot}/usr/share/package-licenses/git-lfs/673c1bf3cbc700ee9fbff87e0c5d297d7a4f2f32 || :
cp %{_builddir}/git-lfs-%{version}/debian/copyright %{buildroot}/usr/share/package-licenses/git-lfs/ea4870f849b8f222e68d5659ab9d340b4aa74bd8 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/alexbrainman/sspi/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/7f7a12bcfc16fab2522aa1a562fd3d2aee429d3b || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/avast/retry-go/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/db3f5d743ce9f0516b533401536f69c891ac6614 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/davecgh/go-spew/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/d2f340a01dd48b589a70f627cf7058c585a315e4 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/dpotapov/go-spnego/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/abb904355d2b6dbba7f2d3c2681d6b3c58e46ad2 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/git-lfs/gitobj/v2/LICENSE.md %{buildroot}/usr/share/package-licenses/git-lfs/1879a048d2441d2634d0056f81317af113e782b8 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/git-lfs/go-netrc/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/ee18887653cb7c7576ca970aa4f6a68213ed8ab2 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/git-lfs/pktline/LICENSE.md %{buildroot}/usr/share/package-licenses/git-lfs/e625eb5894ea9ed23037b013c5391ca07cf6a76a || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/git-lfs/wildmatch/v2/LICENSE.md %{buildroot}/usr/share/package-licenses/git-lfs/c743d26775049fc2c4402bdee3007d63cf6181d4 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/hashicorp/go-uuid/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/fa7c4d75bae3a641d1f9ab5df028175bfb8a69ca || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/inconshreveable/mousetrap/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/62446e71c226403f1a2e67d0f66ede03e3fbdd2f || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/jcmturner/aescts/v2/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/jcmturner/dnsutils/v2/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/jcmturner/gofork/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/d6a5f1ecaedd723c325a2063375b3517e808a2b5 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/jcmturner/goidentity/v6/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/jcmturner/gokrb5/v8/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/jcmturner/rpc/v2/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/leonelquinteros/gotext/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/f4c26c28c2455b6a57bc272711025451e88dcf7e || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/mattn/go-isatty/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/5b53018d7f0706e49275a92d36b54cfbfbb71367 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/olekukonko/ts/LICENCE %{buildroot}/usr/share/package-licenses/git-lfs/0c877fce48e777778681b1dff7df4bcfc281f19b || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/pkg/errors/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/9c1bedc0d42f24c24a1bd266f3ce101a4b0579fc || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/pmezard/go-difflib/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/cd3e4d932cee20da681e6b3bee8139cb4f734034 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/rubyist/tracerx/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/dd6a133536dcf51a25a50850e21971c4a22f9f5f || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/spf13/cobra/LICENSE.txt %{buildroot}/usr/share/package-licenses/git-lfs/c7feacb4667f8c63c89e2eeeb9a913bd3ced8ac2 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/spf13/pflag/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/b3c86ae465b21f7323059db335158b48187731c7 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/ssgelm/cookiejarparser/LICENSE.md %{buildroot}/usr/share/package-licenses/git-lfs/3f3cea798c0ca447dc85bada07c5e05bc5c8d74d || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/stretchr/testify/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/892204393ca075d09c8b1c1d880aba1ae0a2b805 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/xeipuuv/gojsonpointer/LICENSE-APACHE-2.0.txt %{buildroot}/usr/share/package-licenses/git-lfs/b7173385030ef97bce57b5b4b78b48763c83aed3 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/xeipuuv/gojsonreference/LICENSE-APACHE-2.0.txt %{buildroot}/usr/share/package-licenses/git-lfs/b7173385030ef97bce57b5b4b78b48763c83aed3 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/github.com/xeipuuv/gojsonschema/LICENSE-APACHE-2.0.txt %{buildroot}/usr/share/package-licenses/git-lfs/b7173385030ef97bce57b5b4b78b48763c83aed3 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/golang.org/x/crypto/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/d6a5f1ecaedd723c325a2063375b3517e808a2b5 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/golang.org/x/net/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/d6a5f1ecaedd723c325a2063375b3517e808a2b5 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/golang.org/x/sync/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/d6a5f1ecaedd723c325a2063375b3517e808a2b5 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/golang.org/x/sys/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/d6a5f1ecaedd723c325a2063375b3517e808a2b5 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/golang.org/x/text/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/d6a5f1ecaedd723c325a2063375b3517e808a2b5 || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/gopkg.in/yaml.v3/LICENSE %{buildroot}/usr/share/package-licenses/git-lfs/b74b3b31bc15ad5e94fc1947d682aa3d84132fce || :
cp %{_builddir}/git-lfs-vendor-%{version}/vendor/gopkg.in/yaml.v3/NOTICE %{buildroot}/usr/share/package-licenses/git-lfs/9522d95b2b9b284285cc3fb6ecc445aa3ee5e785 || :
export GOAMD64=v2
GOAMD64=v2
install -Dm755 bin/git-lfs %{buildroot}/usr/bin/git-lfs
## install_append content
install -Dm644 git-lfs.bash %{buildroot}/usr/share/bash-completion/completions/git-lfs
pushd man
for man in man*; do
section=${man:3}
mkdir -p %{buildroot}/usr/share/man/${man}
install -D -p -m 0644 ${man}/*.${section} %{buildroot}/usr/share/man/${man}/
done
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/git-lfs

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/git-lfs

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/git-lfs/0c877fce48e777778681b1dff7df4bcfc281f19b
/usr/share/package-licenses/git-lfs/1879a048d2441d2634d0056f81317af113e782b8
/usr/share/package-licenses/git-lfs/3f3cea798c0ca447dc85bada07c5e05bc5c8d74d
/usr/share/package-licenses/git-lfs/5b53018d7f0706e49275a92d36b54cfbfbb71367
/usr/share/package-licenses/git-lfs/62446e71c226403f1a2e67d0f66ede03e3fbdd2f
/usr/share/package-licenses/git-lfs/673c1bf3cbc700ee9fbff87e0c5d297d7a4f2f32
/usr/share/package-licenses/git-lfs/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/git-lfs/7f7a12bcfc16fab2522aa1a562fd3d2aee429d3b
/usr/share/package-licenses/git-lfs/892204393ca075d09c8b1c1d880aba1ae0a2b805
/usr/share/package-licenses/git-lfs/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/git-lfs/9522d95b2b9b284285cc3fb6ecc445aa3ee5e785
/usr/share/package-licenses/git-lfs/9c1bedc0d42f24c24a1bd266f3ce101a4b0579fc
/usr/share/package-licenses/git-lfs/abb904355d2b6dbba7f2d3c2681d6b3c58e46ad2
/usr/share/package-licenses/git-lfs/b3c86ae465b21f7323059db335158b48187731c7
/usr/share/package-licenses/git-lfs/b7173385030ef97bce57b5b4b78b48763c83aed3
/usr/share/package-licenses/git-lfs/b74b3b31bc15ad5e94fc1947d682aa3d84132fce
/usr/share/package-licenses/git-lfs/c743d26775049fc2c4402bdee3007d63cf6181d4
/usr/share/package-licenses/git-lfs/c7feacb4667f8c63c89e2eeeb9a913bd3ced8ac2
/usr/share/package-licenses/git-lfs/cd3e4d932cee20da681e6b3bee8139cb4f734034
/usr/share/package-licenses/git-lfs/d2f340a01dd48b589a70f627cf7058c585a315e4
/usr/share/package-licenses/git-lfs/d6a5f1ecaedd723c325a2063375b3517e808a2b5
/usr/share/package-licenses/git-lfs/db3f5d743ce9f0516b533401536f69c891ac6614
/usr/share/package-licenses/git-lfs/dd6a133536dcf51a25a50850e21971c4a22f9f5f
/usr/share/package-licenses/git-lfs/e625eb5894ea9ed23037b013c5391ca07cf6a76a
/usr/share/package-licenses/git-lfs/ea4870f849b8f222e68d5659ab9d340b4aa74bd8
/usr/share/package-licenses/git-lfs/ee18887653cb7c7576ca970aa4f6a68213ed8ab2
/usr/share/package-licenses/git-lfs/f4c26c28c2455b6a57bc272711025451e88dcf7e
/usr/share/package-licenses/git-lfs/fa7c4d75bae3a641d1f9ab5df028175bfb8a69ca

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/git-lfs-checkout.1
/usr/share/man/man1/git-lfs-clean.1
/usr/share/man/man1/git-lfs-clone.1
/usr/share/man/man1/git-lfs-completion.1
/usr/share/man/man1/git-lfs-dedup.1
/usr/share/man/man1/git-lfs-env.1
/usr/share/man/man1/git-lfs-ext.1
/usr/share/man/man1/git-lfs-fetch.1
/usr/share/man/man1/git-lfs-filter-process.1
/usr/share/man/man1/git-lfs-fsck.1
/usr/share/man/man1/git-lfs-install.1
/usr/share/man/man1/git-lfs-lock.1
/usr/share/man/man1/git-lfs-locks.1
/usr/share/man/man1/git-lfs-logs.1
/usr/share/man/man1/git-lfs-ls-files.1
/usr/share/man/man1/git-lfs-merge-driver.1
/usr/share/man/man1/git-lfs-migrate.1
/usr/share/man/man1/git-lfs-pointer.1
/usr/share/man/man1/git-lfs-post-checkout.1
/usr/share/man/man1/git-lfs-post-commit.1
/usr/share/man/man1/git-lfs-post-merge.1
/usr/share/man/man1/git-lfs-pre-push.1
/usr/share/man/man1/git-lfs-prune.1
/usr/share/man/man1/git-lfs-pull.1
/usr/share/man/man1/git-lfs-push.1
/usr/share/man/man1/git-lfs-smudge.1
/usr/share/man/man1/git-lfs-standalone-file.1
/usr/share/man/man1/git-lfs-status.1
/usr/share/man/man1/git-lfs-track.1
/usr/share/man/man1/git-lfs-uninstall.1
/usr/share/man/man1/git-lfs-unlock.1
/usr/share/man/man1/git-lfs-untrack.1
/usr/share/man/man1/git-lfs-update.1
/usr/share/man/man1/git-lfs.1
/usr/share/man/man5/git-lfs-config.5
/usr/share/man/man7/git-lfs-faq.7
